### PR TITLE
Revert "Fix esm output"

### PR DESCRIPTION
**Pull request by amcdnl**
Reverts reaviz/reaviz#89

### CODE REVIEW

**Comment by danteissaias** [comment]
Whats's the reason for reverting this?

**Comment by danteissaias** [comment]
What's the reason for reverting this?

**Comment by amcdnl** [comment]
Sadly it broke a few things. ESM has been challenging. I want to look at moving to Vite library build off of this manual setup - do you have any experience w/ that?

**Comment by danteissaias** [comment]
No but I will look into it.

**Comment by amcdnl** [comment]
@danteissaias -  Here is an interesting article on it - https://andrewwalpole.com/blog/use-vite-for-javascript-libraries/

**Comment by danteissaias** [comment]
https://github.com/egoist/tsup looks good. PR should land in the next few days.

**Comment by amcdnl** [comment]
@danteissaias - What about vite library mode?

**Pull request merged**
